### ISSUE TITLE
Replace IDL to actual C code and use pycparser to check it

### ISSUE THREAD

**Issue by rodrigopex** [lucaspeixotot/pdb#143]
Current way of defining channel messages.
```yaml
Messages:
  - SENSORS_MSG:
      mtype: union
      fields:
        - a:
            mtype: u8
        - b:
            mtype: u8
        - c:
            mtype: u32
  - NET_REQUEST_MSG:
      mtype: u8
  - NET_RESPONSE_MSG:
      mtype: u8
      size: 5
```

The proposed way of defining channel messages.
```yaml
# The rest of the yaml file...

Messages:
  - SENSORS_MSG: >
      union {
          uint8_t a;
          uint8_t b;
          uint32_t c;
      };

  - NET_REQUEST_MSG: >
      struct {
          uint8_t attr;
      };

  - NET_RESPONSE_MSG: >
      struct {
          uint8_t bytes[a];
      };

```
With the new way of defining messages, we'll need to use only struct or unions as base types.
