### ISSUE TITLE
Enable to describe message inside a channel

### ISSUE THREAD

**Issue by rodrigopex** [lucaspeixotot/pdb#144]
It would be possible to describe a message inside the channel directly instead of describing it as always separated. It will increase readability. The desired result must be something like:

```yaml
Messages:
  - LIGHT_STATUS_MSG: > 
      struct {
          uin8_t on:1;
          uin8_t broken:1;
          uint8_t color: 6;
      };

Channels:
  - FIRMWARE_VERSION:
      message: >
        struct {
            uint8_t major;
            uint8_t minor;
            uint16_t build;
        };

  - SUNLIGHT_LEVEL:
      message: >
        struct {
            int16_t level;
        };
     
  - LIGHT_STATUS:
      message: !ref LIGHT_STATUS_MSG 
      on_changed: True

  - LIGHT_STATUS2:
      message: !ref LIGHT_STATUS_MSG
      on_changed: True

```
This issue depends on the issue #143
