### ISSUE TITLE
Add conditional compilation for a service

### ISSUE THREAD

**Issue by rodrigopex** [lucaspeixotot/pdb#148]
Maybe adding a "depends" field where the service will use to add itself to the project sources or not. 
```
Services:
   - ANALOG_SENSORS:
       depends: CONFIG_SOME_FEATURE 
       priority: 4
       stack_size: 1024
       sub_channels:
         - !ref EXTA_SENSOR_1_FETCH
         - !ref EXTA_SENSOR_2_FETCH
       pub_channels:
         - !ref EXTA_SENSOR_1
         - !ref EXTA_SENSOR_2

```
If CONFIG_SOME_FEATURE is not defined or it is *no*, the source code won't be added to the zeta.cmake file.
